package nominav3;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo Perez
 */
public class nominencabezado extends javax.swing.JFrame {
    String stmtPrincipal[][] = new String[15][3];
    public nominencabezado() {
        initComponents();
        grupo.add(rbtmod);
        grupo.add(rbtvi);
        llenardatos();
        nomostrar();
    }

    public void nomostrar() {
        cmbNom.setVisible(false);
        cmbNomBan.setVisible(false);
        cmbCod.setVisible(false);
        cmbCodBan.setVisible(false);
        txtmonto.setVisible(false);
        l1.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        dtfin.setVisible(false);dtIni.setVisible(false);
        btnvi.setVisible(false);
        jScrollPane1.setVisible(false);
        l2.setVisible(false);
        bntmod.setVisible(false);
    }

    public void llenardatos() {
        //Codigo que permite ingresar datos a los combobox
        this.cmbCod.removeAllItems();
        this.cmbNom.removeAllItems();
        try {
            //conexion de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM `nominaencabezado`");
            ResultSet rs = pst.executeQuery();
            boolean r = rs.next();
            while (r) {
                this.cmbNom.addItem("Del " + (rs.getString("nomi_fechaini")) + " al " + (rs.getString("nom_fechafin")));
                this.cmbCod.addItem(rs.getString("nomi_codigo"));
                r = rs.next();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Base de datos no enlazada");
        }
        this.cmbCodBan.removeAllItems();
        this.cmbNomBan.removeAllItems();
        try {
            //conexion de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM bancos");
            ResultSet rs = pst.executeQuery();
            boolean r = rs.next();
            while (r) {
                this.cmbNomBan.addItem(rs.getString("ban_nombre"));
                this.cmbCodBan.addItem(rs.getString("ban_codigo"));
                r = rs.next();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Base de datos no enlazada");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        rbtvi = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        cmbCod = new javax.swing.JComboBox<>();
        cmbNom = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnvi = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        rbtmod = new javax.swing.JRadioButton();
        bntmod = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();
        cmbNomBan = new javax.swing.JComboBox<>();
        cmbCodBan = new javax.swing.JComboBox<>();
        l3 = new javax.swing.JLabel();
        dtIni = new datechooser.beans.DateChooserPanel();
        dtfin = new datechooser.beans.DateChooserPanel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1384, 632));
        setPreferredSize(new java.awt.Dimension(1384, 632));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtvi.setText("Visualizar");
        rbtvi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtviMouseClicked(evt);
            }
        });
        rbtvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtviActionPerformed(evt);
            }
        });
        getContentPane().add(rbtvi, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, -1, -1));

        jLabel1.setText("Nomina Encabezado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));
        getContentPane().add(txtmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 170, -1));

        l1.setText("Final");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, -1));

        cmbCod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        cmbNom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNomItemStateChanged(evt);
            }
        });
        cmbNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNomActionPerformed(evt);
            }
        });
        getContentPane().add(cmbNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 230, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Monto", "Banco"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 990, 210));

        btnvi.setText("Visualizar");
        btnvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviActionPerformed(evt);
            }
        });
        getContentPane().add(btnvi, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 170, -1));

        l2.setText("Banco");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, -1, -1));

        rbtmod.setText("Modificar");
        rbtmod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtmodMouseClicked(evt);
            }
        });
        getContentPane().add(rbtmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        bntmod.setText("Modificar");
        bntmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntmodActionPerformed(evt);
            }
        });
        getContentPane().add(bntmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 170, -1));

        btnregresar.setBackground(new java.awt.Color(255, 148, 42));
        btnregresar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnregresar.setForeground(new java.awt.Color(190, 243, 85));
        btnregresar.setText("Regresar");
        btnregresar.setMinimumSize(new java.awt.Dimension(763, 439));
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 480, 290, 60));

        cmbNomBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNomBan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNomBanItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbNomBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 160, -1));

        cmbCodBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbCodBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, -1, -1));

        l3.setText("Monto");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, -1, -1));
        getContentPane().add(dtIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 350, 250));
        getContentPane().add(dtfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 360, 250));

        l4.setText("Fecha");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        l5.setText("Inicio");
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtviMouseClicked
        nomostrar();
        jScrollPane1.setVisible(true);
        btnvi.setVisible(true);
        for (int i = 0; i <= 14; i++) {
            for (int y = 0; y <= 2; y++) {
                stmtPrincipal[i][y] = "";
            }
        }
        tabla.setModel(new javax.swing.table.DefaultTableModel(
                stmtPrincipal,
                new String[]{
                    "Fecha", "Monto", "Banco"
                }
        ));
    }//GEN-LAST:event_rbtviMouseClicked

    private void cmbNomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNomItemStateChanged
        try {
            cmbCod.setSelectedIndex(cmbNom.getSelectedIndex());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cmbNomItemStateChanged

    private void cmbNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNomActionPerformed

    private void btnviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviActionPerformed
        //Codigo que permite consultar registros en la base de datos
        int x = 0, itEstado;//variable para la matriz
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT nominaencabezado.nomi_fechaini,nominaencabezado.nom_fechafin, nominaencabezado.nomi_monto, bancos.ban_nombre, bancos.ban_cuenta FROM `nominaencabezado`, bancos WHERE nominaencabezado.ban_codigo=bancos.ban_codigo");
            ResultSet rs = pst.executeQuery();
            boolean r = rs.next();
            while (r) {
                stmtPrincipal[x][0] = "Del "+rs.getString("nomi_fechaini")+" al "+rs.getString("nom_fechafin");
                stmtPrincipal[x][1] = rs.getString("nomi_monto");
                stmtPrincipal[x][2] =rs.getString("ban_nombre")+" "+ rs.getString("ban_cuenta");
                r = rs.next();
                x++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "le dio un Error fatal");
        }
        //codigo para mostrarlo en la matriz
        tabla.setModel(new javax.swing.table.DefaultTableModel(
                stmtPrincipal,
                new String[]{
                    "Codigo", "Nombre", "No. cuenta"
                }
        ));
        for (int i = 0; i <= 14; i++) {
            for (int y = 0; y <= 2; y++) {
                stmtPrincipal[i][y] = "";
            }
        }
    }//GEN-LAST:event_btnviActionPerformed

    private void rbtmodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtmodMouseClicked
        nomostrar();
        llenardatos();
        cmbNom.setVisible(true);
        cmbNomBan.setVisible(true);
        txtmonto.setVisible(true);
        l1.setVisible(true);
        l3.setVisible(true);
        dtfin.setVisible(true);dtIni.setVisible(true);
        l2.setVisible(true);l4.setVisible(true);l5.setVisible(true);
        bntmod.setVisible(true);
    }//GEN-LAST:event_rbtmodMouseClicked

    private void bntmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntmodActionPerformed
        //codigos para guardar el nuevo dato en la tabla departamentos
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            PreparedStatement pst = cn.prepareStatement("UPDATE `nominaencabezado` SET `nomi_fechaini`='"+dtIni.getSelection()+"',`nom_fechafin`='"+dtfin.getSelection()+"',`nomi_monto`='"+txtmonto.getText()+"',`ban_codigo`='"+cmbCodBan.getSelectedItem()+"' WHERE `nomi_codigo`='"+cmbCod.getSelectedItem()+"'");
            pst.executeUpdate();
            txtmonto.setText("");
            JOptionPane.showMessageDialog(null, "Dato guardado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "le dio un error " + e);
        }
        llenardatos();
    }//GEN-LAST:event_bntmodActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed

        menu pantalla = new menu();
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnregresarActionPerformed

    private void cmbNomBanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNomBanItemStateChanged
            try {
            cmbCodBan.setSelectedIndex(cmbNomBan.getSelectedIndex());
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_cmbNomBanItemStateChanged

    private void rbtviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nominencabezado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nominencabezado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nominencabezado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nominencabezado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nominencabezado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntmod;
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton btnvi;
    private javax.swing.JComboBox<String> cmbCod;
    private javax.swing.JComboBox<String> cmbCodBan;
    private javax.swing.JComboBox<String> cmbNom;
    private javax.swing.JComboBox<String> cmbNomBan;
    private datechooser.beans.DateChooserPanel dtIni;
    private datechooser.beans.DateChooserPanel dtfin;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JRadioButton rbtmod;
    private javax.swing.JRadioButton rbtvi;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtmonto;
    // End of variables declaration//GEN-END:variables
}

