package nominav3;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Ricardo perez
 */
public class usuarios extends javax.swing.JFrame {
int j1;
    String stmtPrincipal[][]=new String[15][5];  
    public usuarios() {
         initComponents();
        grupo.add(rbtel);
        grupo2.add(rbtm);grupo2.add(rbtme);
        grupo.add(rbtvi);grupo.add(rbtin);
        nomostrar();
        codigoauto();
        llenardatos();
    }
public void nomostrar(){
cmbNom.setVisible(false);
cmbNomEmp.setVisible(false);
cmbCodEmp.setVisible(false);
cmbCod.setVisible(false);
txtcontra.setVisible(false);
l2.setVisible(false);
l3.setVisible(false);
txtnom.setVisible(false);
l1.setVisible(false);
btnin.setVisible(false);
btnvi.setVisible(false);
btnel.setVisible(false);
jScrollPane1.setVisible(false);
rbtm.setVisible(false);
rbtme.setVisible(false);

}
 public void codigoauto(){
        //codigo para saber cuantas lineas hay en la base de datos y asi poder llenar el codigo sin ingresar
        j1=0;
          try {              
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            Statement s=con.createStatement();
           String SQL="SELECT * FROM usuario";
           ResultSet rs=s.executeQuery(SQL);
            boolean r=rs.next();
            while(r){
                j1=j1+1;
                r=rs.next();            
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Conexión erronea"+e);
        }
    }
 public void llenardatos(){
   //Codigo que permite ingresar datos a los listas
      this.cmbCod.removeAllItems();
      this.cmbNom.removeAllItems();
      this.cmbCodEmp.removeAllItems();
      this.cmbNomEmp.removeAllItems();
         //Codigo que permite ingresar datos a los listas
        try{
            //conexion de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM empleados");
            ResultSet rs = pst.executeQuery();
            boolean r=rs.next();
            while(r){
                this.cmbNomEmp.addItem(rs.getString("emp_nombre"));
                this.cmbCodEmp.addItem(rs.getString("emp_codigo"));
                r=rs.next();            
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Base de datos no enlazada");
        }
                try{
            //conexion de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM usuario");
            ResultSet rs = pst.executeQuery();
            boolean r=rs.next();
            while(r){
                this.cmbNom.addItem(rs.getString("us_nombre"));
                this.cmbCod.addItem(rs.getString("us_codigo"));
                r=rs.next();            
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Base de datos no enlazada");
        }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        grupo2 = new javax.swing.ButtonGroup();
        rbtin = new javax.swing.JRadioButton();
        rbtel = new javax.swing.JRadioButton();
        rbtvi = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnin = new javax.swing.JButton();
        txtnom = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        cmbCod = new javax.swing.JComboBox<>();
        cmbNom = new javax.swing.JComboBox<>();
        btnel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnvi = new javax.swing.JButton();
        rbtme = new javax.swing.JRadioButton();
        rbtm = new javax.swing.JRadioButton();
        txtcontra = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        cmbNomEmp = new javax.swing.JComboBox<>();
        cmbCodEmp = new javax.swing.JComboBox<>();
        l3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1023, 529));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtin.setText("Ingresar");
        rbtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtinMouseClicked(evt);
            }
        });
        getContentPane().add(rbtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        rbtel.setText("Modificar");
        rbtel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtelMouseClicked(evt);
            }
        });
        getContentPane().add(rbtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        rbtvi.setText("Visualizar");
        rbtvi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtviMouseClicked(evt);
            }
        });
        getContentPane().add(rbtvi, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jLabel1.setText("Concepto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        btnin.setText("Ingresar");
        btnin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninActionPerformed(evt);
            }
        });
        getContentPane().add(btnin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 170, -1));
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 170, -1));

        l1.setText("Nombre");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, 20));

        cmbCod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        cmbNom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNomItemStateChanged(evt);
            }
        });
        cmbNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNomActionPerformed(evt);
            }
        });
        getContentPane().add(cmbNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 170, -1));

        btnel.setText("Modificar");
        btnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelActionPerformed(evt);
            }
        });
        getContentPane().add(btnel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 170, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "codigo", "nombre", "Efecto"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 640, 140));

        btnvi.setText("Visualizar");
        btnvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviActionPerformed(evt);
            }
        });
        getContentPane().add(btnvi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 170, -1));

        rbtme.setText("Inactivo");
        rbtme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtmeMouseClicked(evt);
            }
        });
        getContentPane().add(rbtme, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, -1, -1));

        rbtm.setText("Activo");
        getContentPane().add(rbtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, -1, -1));
        getContentPane().add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 170, -1));

        l2.setText("Empleado");
        l2.setToolTipText("");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, 20));

        cmbNomEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNomEmp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNomEmpItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbNomEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 170, -1));

        cmbCodEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbCodEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        l3.setText("Contraseña");
        l3.setToolTipText("");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtinMouseClicked
        nomostrar();
    cmbNomEmp.setVisible(true);
    txtcontra.setVisible(true);
    l2.setVisible(true);
    l3.setVisible(true);
    txtnom.setVisible(true);
    l1.setVisible(true);
    btnin.setVisible(true);
    rbtm.setVisible(true);
    rbtme.setVisible(true);
    }//GEN-LAST:event_rbtinMouseClicked

    private void rbtelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtelMouseClicked
        nomostrar();
        llenardatos();
    cmbNomEmp.setVisible(true);
    txtcontra.setVisible(true);
    txtnom.setVisible(true);
    l2.setVisible(true);
    l3.setVisible(true);
    cmbNom.setVisible(true);
    l1.setVisible(true);
    btnel.setVisible(true);
    rbtm.setVisible(true);
    rbtme.setVisible(true);
    }//GEN-LAST:event_rbtelMouseClicked

    private void rbtviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtviMouseClicked
        nomostrar();
        jScrollPane1.setVisible(true);
        btnvi.setVisible(true);
        for(int i=0;i<=14;i++){
            for(int y=0;y<=2;y++){
                stmtPrincipal[i][y]="";
            }
        }
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            stmtPrincipal,
            new String [] {
                "Codigo", "Nombre","Efecto"
            }
        ));
    }//GEN-LAST:event_rbtviMouseClicked

    private void btninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninActionPerformed
        //codigos para guardar el nuevo dato en la tabla departamentos
        codigoauto();        
        int itEstado=0;       
        if(rbtm.isSelected()){itEstado=2;}else{itEstado=1;}
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            PreparedStatement pst = cn.prepareStatement("INSERT INTO `usuario`(`us_codigo`, `us_nombre`, `us_clave`, `us_estadousuario`, `emp_codi`) VALUES ('"+(j1+1)+"','"+txtnom.getText().trim()+"','"+txtcontra.getText().trim()+"','"+itEstado+"','"+cmbCodEmp.getSelectedItem()+"');");
            pst.executeUpdate();
            txtnom.setText("");txtcontra.setText("");
            JOptionPane.showMessageDialog(null,"Dato guardado con exito");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"le dio un error "+e);
        }
    }//GEN-LAST:event_btninActionPerformed

    private void cmbNomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNomItemStateChanged
        try{ cmbCod.setSelectedIndex(cmbNom.getSelectedIndex());}
        catch(Exception e){
        }
    }//GEN-LAST:event_cmbNomItemStateChanged

    private void cmbNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNomActionPerformed

    private void btnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelActionPerformed
         //codigos para guardar el nuevo dato en la tabla departamentos
        codigoauto();        
        int itEstado=0;       
        if(rbtm.isSelected()){itEstado=2;}else{itEstado=1;}
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            PreparedStatement pst = cn.prepareStatement("UPDATE `usuario` SET `us_nombre`='"+txtnom.getText().trim()+"', `us_clave`='"+txtcontra.getText().trim()+"',`us_estadousuario`='"+itEstado+"',`emp_codi`='"+cmbCodEmp.getSelectedItem()+"' WHERE us_codigo="+cmbCod.getSelectedItem()+"");
            pst.executeUpdate();
            txtnom.setText("");txtcontra.setText("");
            JOptionPane.showMessageDialog(null,"Dato guardado con exito");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"le dio un error "+e);
        }
              llenardatos();
    }//GEN-LAST:event_btnelActionPerformed

    private void btnviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviActionPerformed
        //Codigo que permite consultar registros en la base de datos
        int itEfecto,x=0,itEstado;//variable para la matriz
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT usuario.us_codigo, usuario.us_nombre, usuario.us_clave, empleados.emp_nombre, usuario.us_estadousuario FROM `usuario`, `empleados` WHERE usuario.emp_codi=empleados.emp_codigo");
            ResultSet rs = pst.executeQuery();
            boolean r=rs.next();
            while(r){
                stmtPrincipal[x][0]=rs.getString("us_codigo");
                stmtPrincipal[x][1]=rs.getString("us_nombre");
                stmtPrincipal[x][2]=rs.getString("us_clave");
                stmtPrincipal[x][3]=rs.getString("emp_nombre");
                if((Integer.parseInt(rs.getString("us_estadousuario"))==1)){
                    stmtPrincipal[x][4]="Inactivo";
                }else{stmtPrincipal[x][4]="Activo";}
                r=rs.next();
                x++;
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"le dio un Error fatal");
        }
        //codigo para mostrarlo en la matriz
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            stmtPrincipal,
            new String [] {
                "Codigo", "Nombre","Contraseña","Empleado","Estado"
            }
        ));
        for(int i=0;i<=14;i++){
            for(int y=0;y<=4;y++){
                stmtPrincipal[i][y]="";
            }
        }
    }//GEN-LAST:event_btnviActionPerformed

    private void rbtmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtmeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtmeMouseClicked

    private void cmbNomEmpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNomEmpItemStateChanged
          try{ cmbCodEmp.setSelectedIndex(cmbNomEmp.getSelectedIndex());}
        catch(Exception e){
        }
    }//GEN-LAST:event_cmbNomEmpItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnel;
    private javax.swing.JButton btnin;
    private javax.swing.JButton btnvi;
    private javax.swing.JComboBox<String> cmbCod;
    private javax.swing.JComboBox<String> cmbCodEmp;
    private javax.swing.JComboBox<String> cmbNom;
    private javax.swing.JComboBox<String> cmbNomEmp;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.ButtonGroup grupo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JRadioButton rbtel;
    private javax.swing.JRadioButton rbtin;
    private javax.swing.JRadioButton rbtm;
    private javax.swing.JRadioButton rbtme;
    private javax.swing.JRadioButton rbtvi;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtcontra;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}

